In [35]:
import pandas as pd
import numpy as np
import pingouin as pg

TASK 1: NHẬP KHẨU DỮ LIỆU

In [36]:
path = 'data_python.csv'
dataframe = pd.read_csv(path)
df = dataframe
df.head()

,Ho_va_ten,So_dien_thoai_hoac_email,Gioi_tinh,Do_tuoi,Tham_nien_cong_tac,Noi_lam_viec,Nganh,Chuc_vu,Bo_phan,Loai_hinh_doanh_nghiep,...,TT4,GS1,GS2,GS2.1,GS4,HH1,HH2,HH3,HH4,HH5
0,Kieu Anh,ngothikieuanh281002@gmail.com,Nu,Duoi 30,Tu 1 den duoi 3 nam,Tap doan Hoa Sen,Ton thep,Nhan vien,Ke toan,Cong ty co phan,...,5,5,4,3,3,5,5,5,4,3
1,Dang Bao Ngan,708631096,Nu,Duoi 30,Tu 3 den duoi 5 nam,Thep Nam Kim,Ton thep,Nhan vien,Tai chinh,Cong ty co phan,...,3,5,4,4,3,5,4,4,5,5
2,Tran Cao Nam Anh,trancaonamanh93@gmail.com,Nu,Duoi 30,Tu 3 den duoi 5 nam,Tap doan Hoa Sen,Ton thep,Nhan vien,Ke toan,Cong ty co phan,...,4,4,4,5,5,2,5,3,4,3
3,Nguyen Cong Hung,981163301,Nam,Tu 30 den 39,Tu 5 den duoi 10 nam,Tap doan Hoa Sen,Ton thep,Giam doc/ Pho giam doc,Mua hang,Cong ty co phan,...,5,5,5,5,4,4,3,5,5,4
4,Ho Dieu,325791256,Nu,Duoi 30,Tu 1 den duoi 3 nam,Ton Dong A,Ton thep,Nhan vien,Ke toan,Cong ty co phan,...,3,4,4,3,4,2,3,5,4,5

TASK 2: LÀM SẠCH DỮ LIỆU

In [37]:
#2.1 Check Null Values

df.isnull().sum()

Ho_va_ten                    0
So_dien_thoai_hoac_email    17
Gioi_tinh                    0
Do_tuoi                      0
Tham_nien_cong_tac           0
Noi_lam_viec                 0
Nganh                        0
Chuc_vu                      0
Bo_phan                      0
Loai_hinh_doanh_nghiep       0
Linh_vuc_hoat_dong           0
Quy_mo                       0
MT1                          0
MT2                          0
MT3                          0
MT4                          0
MT5                          0
MT6                          0
MT7                          0
MT8                          0
MT9                          0
MT10                         0
MT11                         0
MT12                         0
MT13                         0
MT14                         0
RR1                          0
RR2                          0
RR3                          0
RR4                          0
RR5                          0
RR6                          0
KS1                          0
KS2                          0
KS3                          0
KS4                          0
KS5                          0
KS6                          0
KS7                          0
KS8                          0
KS9                          0
KS10                         0
KS11                         0
KS12                         0
KS13                         0
TT1                          0
TT2                          0
TT3                          0
TT4                          0
GS1                          0
GS2                          0
GS2.1                        0
GS4                          0
HH1                          0
HH2                          0
HH3                          0
HH4                          0
HH5                          0
dtype: int64

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 58 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Ho_va_ten                 91 non-null     object
 1   So_dien_thoai_hoac_email  74 non-null     object
 2   Gioi_tinh                 91 non-null     object
 3   Do_tuoi                   91 non-null     object
 4   Tham_nien_cong_tac        91 non-null     object
 5   Noi_lam_viec              91 non-null     object
 6   Nganh                     91 non-null     object
 7   Chuc_vu                   91 non-null     object
 8   Bo_phan                   91 non-null     object
 9   Loai_hinh_doanh_nghiep    91 non-null     object
 10  Linh_vuc_hoat_dong        91 non-null     object
 11  Quy_mo                    91 non-null     object
 12  MT1                       91 non-null     int64
 13  MT2                       91 non-null     int64
 14  MT3                       91 non-null     int64
 15  MT4                       91 non-null     int64
 16  MT5                       91 non-null     int64
 17  MT6                       91 non-null     int64
 18  MT7                       91 non-null     int64
 19  MT8                       91 non-null     int64
 20  MT9                       91 non-null     int64
 21  MT10                      91 non-null     int64
 22  MT11                      91 non-null     int64
 23  MT12                      91 non-null     int64
 24  MT13                      91 non-null     int64
 25  MT14                      91 non-null     int64
 26  RR1                       91 non-null     int64
 27  RR2                       91 non-null     int64
 28  RR3                       91 non-null     int64
 29  RR4                       91 non-null     int64
 30  RR5                       91 non-null     int64
 31  RR6                       91 non-null     int64
 32  KS1                       91 non-null     int64
 33  KS2                       91 non-null     int64
 34  KS3                       91 non-null     int64
 35  KS4                       91 non-null     int64
 36  KS5                       91 non-null     int64
 37  KS6                       91 non-null     int64
 38  KS7                       91 non-null     int64
 39  KS8                       91 non-null     int64
 40  KS9                       91 non-null     int64
 41  KS10                      91 non-null     int64
 42  KS11                      91 non-null     int64
 43  KS12                      91 non-null     int64
 44  KS13                      91 non-null     int64
 45  TT1                       91 non-null     int64
 46  TT2                       91 non-null     int64
 47  TT3                       91 non-null     int64
 48  TT4                       91 non-null     int64
 49  GS1                       91 non-null     int64
 50  GS2                       91 non-null     int64
 51  GS2.1                     91 non-null     int64
 52  GS4                       91 non-null     int64
 53  HH1                       91 non-null     int64
 54  HH2                       91 non-null     int64
 55  HH3                       91 non-null     int64
 56  HH4                       91 non-null     int64
 57  HH5                       91 non-null     int64
dtypes: int64(46), object(12)
memory usage: 41.4+ KB

--> Do đó, dữ liệu không có khoản trắng. Ngoại từ cột "So_dien_thoai_hoac_email", trường dữ liệu cột này không quan trọng cho nghiên cứu, do đó không nhất thiết phải đầy đủ.

In [39]:
##2.2 Check values of all columns

column_headers = list(df.columns.values)
n = len(df.columns)
for i in range(n):
    print(i, end = " ")
    print('- ', end = " ")
    print(column_headers[i], end = " ")
    print(set(df[column_headers[i]]))

0 -  Ho_va_ten {'Nguyen Minh Quan', 'Nguyen Minh Hien', 'Pham Van Dinh', 'Nguyen Hoang Duc', 'Phan Thi Ngoc Chi', 'Nguyen Thi Cam Ty', 'Nguyen Hoang To Loan', 'Luu Thi My Thanh', 'Tran Dinh Nam', 'Nguyen Thai Khanh Huyen', 'Do Thi Thanh Huyen', 'Cao Phuong Mai', 'Nguyen Thi Loan ', 'Tran Van Bao', 'Nguyen Thi Thanh Tam', 'Nguyen Thi Ha Phuong', 'Tran Dang Khoa', 'Nguyen Truc Phuong', 'Nguyen Van An', 'Tran Thi Thu Quyen ', 'Nguyen Thanh Tung', 'Tran Thanh Do', 'Nguyen Ngoc Tran', 'Le Thi Bao Ngoc', 'Nguyen Thi Kim Thu', 'Nguyen Quoc Nhi Bac', 'Le Thi Ngoc Han ', 'Ngo Minh Tri', 'Doan Thi My Ngan', 'Dang Thuy Duong', 'Bui Nhan Tran', 'Vu Thi Minh Phuong ', 'Le Thi Lam', 'Nguyen Van Thi', 'Hoang Mai Anh Dung', 'Phan Tien Cuong', 'Nguyen Thi Thanh Trang', 'Pham Thi Thuy Nhung', 'Nguyen Tu Minh', 'Dang Hai Son', 'Nguyen Thi Thanh Ha', 'Phan Tam', 'Phan Dieu', 'Nguyen Cong Hung', 'Do Thi Mai Xuon', 'Nguyen Le Gia Han', 'Pham Thi Minh Thu', 'Le Thi Ngoc Tram', 'Nguyen Thi Thuy Duong ', 'Ho Thi Mai Trinh', 'Le Thi Tuong Van', 'Pham Nguyen Phuong Uyen', 'Hoang Thi Hai Yen', 'Nguyen Thi To Trang', 'Truong Ngoc', 'Nguyen Sy Tra My', 'Pham Truc Quynh', 'Nguyen Tran Kim Hanh', 'Dang Bao Ngan', 'Kieu Anh', 'Nguyen Thi Ngoc My', 'Le Thi Duyen', 'Dao Thi Phuong', 'Nguyen Hoang Anh', 'Le Thi Minh Thu', 'Nguyen Thi Thanh Diem', 'Bui Hong Dao', 'Ho Dieu', 'Pham Tien Hung', 'Tran Cao Nam Anh', 'Phan Quoc Viet', 'Nguyen Thi Xuan Ha ', 'Nguyen Nu Ai Loan', 'Nguyen Nhut Duy', 'Nguyen Thanh Thi', 'Pham Thi Ngoc Bich', 'Bui Hoang Viet Anh', 'Tran Thi Thanh Phuong', 'Dang Ngan Ha', 'Bui Tran Anh', 'Ho Van Hong Hanh', 'Do Hong Ngoc', 'Tran Thi Quynh Nhu', 'Vu Thi Thu', 'Lu Ngoc My Huyen', 'Pham Thi Thanh', 'Nguyen Hoang Bao An', 'Chu Thi Huyen', 'Do Thanh Phuong ', 'Tran Thi Huong'}
1 -  So_dien_thoai_hoac_email {'708631096', '379330303', 'nguyenthicamtu5950@gmail.com', 'Ngocmy3108@gmail.com', '343556856', 'doanthimynganb2@gmail.com', '964215414', 'dinhnam98@gmail.com', 'buitrananh9@gmail.com', '931474820', '355482750', 'ptnbich@ueh.edu.vn', '983492442', 'nlgiahan@gmail.com', '363803525', 'bongxinh.199x@gmail.com', '965775005', 'Ntthanhdiem2198@gmail.com ', 'phuonguyen120102@gmail.com', '388527725', 'loannht@ueh.edu.vn', nan, '981163301', '919846776', '923713103', '798674776', '935294743', '931774966', '981204253', '398017515', '975852312', 'trucquynh262002@gmail.com', '325791256', 'thanhphuong752000@gmail.com', 'ngochan04032000@gmail.com ', '357597918', '326575809', '909397727', 'annguyen.3119@gmail.com', '976894036', '394123919', 'minhthi.cshcm@imap.edu.vn', 'thuthuvo0109@gmail.com', '966581065', '377857054', 'ngochong.do95@gmail.com', 'phantiencuongueh@gmail.com', 'ltbaongoc2002@gmail.com', '354914207', '938225481', '767741375', 'Nguyenngoctran2599@gmail.com', 'lnmyhuyen@gmail.com', '912352162', 'tranthanhdo99@gmail.com', '366736024', '931941046', '963693914', '338799648', 'hoanghaiyen.1999@gmail.com', '916741855', '339928254', 'ttqn13062002@gmail.com', '378348522', '985828842', '937982604', '985795928', 'mtrinh2405@gmail.com', '971856827', '932916243', '389286105', '6363nhutduy@gmail.com', 'ngothikieuanh281002@gmail.com', 'trancaonamanh93@gmail.com', '762423387'}
2 -  Gioi_tinh {'Nu', 'Nam'}
3 -  Do_tuoi {'Tu 50 tro len', 'Tu 30 den 39', 'Duoi 30', 'Tu 40 den 49'}
4 -  Tham_nien_cong_tac {'Tu 1 den duoi 3 nam', 'Tu 3 den duoi 5 nam', 'Tu 5 den duoi 10 nam', 'Duoi 1 nam', 'Tu 10 nam tro len'}
5 -  Noi_lam_viec {'Tap doan Hoa Sen', 'Khac', 'Co khi Thu Duc', 'A74', 'Ton thep Sai Gon', 'Dai hoc Kinh te TP. HCM', 'Lam Huynh Phat', 'Tap doan Hoa Phat', 'Thep Nam Kim', 'Ton thep Kim Lan', 'Tap doan Loc Troi', 'Song Thu', 'Ton thep Tan Dat', 'Trung Minh Hung', 'Van Truong Phat', 'Tahara', 'Ton Dong A'}
6 -  Nganh {'Khong phai Ton thep', 'Ton thep'}
7 -  Chuc_vu {'Truong phong/ Pho phong', 'Giam doc/ Pho giam doc', 'Nhan vien', 'To truong/ To pho', 'Giang vien'}
8 -  Bo_phan {'Ban hang', 'Ban giam doc', 'Ke toan', 'Hanh chinh', 'Ky thuat', 'Kiem toan noi bo', 'Kiem toan', 'Mua hang', 'Tai chinh', 'Marketing ', 'Kiem soat noi bo'}
9 -  Loai_hinh_doanh_nghiep {'Dai hoc cong lap', 'Cong ty TNHH', 'Cong ty co phan'}
10 -  Linh_vuc_hoat_dong {'Gia cong', 'Giao duc', 'San xuat', 'Thuong mai'}
11 -  Quy_mo {'Doanh nghiep vua', 'Doanh nghiep lon', 'Doanh nghiep nho'}
12 -  MT1 {2, 3, 4, 5}
13 -  MT2 {1, 2, 3, 4, 5}
14 -  MT3 {2, 3, 4, 5}
15 -  MT4 {2, 3, 4, 5}
16 -  MT5 {2, 3, 4, 5}
17 -  MT6 {3, 4, 5}
18 -  MT7 {2, 3, 4, 5}
19 -  MT8 {3, 4, 5}
20 -  MT9 {3, 4, 5}
21 -  MT10 {3, 4, 5}
22 -  MT11 {2, 3, 4, 5}
23 -  MT12 {3, 4, 5}
24 -  MT13 {2, 3, 4, 5}
25 -  MT14 {3, 4, 5}
26 -  RR1 {3, 4, 5}
27 -  RR2 {3, 4, 5}
28 -  RR3 {2, 3, 4, 5}
29 -  RR4 {3, 4, 5}
30 -  RR5 {3, 4, 5}
31 -  RR6 {3, 4, 5}
32 -  KS1 {3, 4, 5}
33 -  KS2 {2, 3, 4, 5}
34 -  KS3 {3, 4, 5}
35 -  KS4 {3, 4, 5}
36 -  KS5 {2, 3, 4, 5}
37 -  KS6 {3, 4, 5}
38 -  KS7 {3, 4, 5}
39 -  KS8 {3, 4, 5}
40 -  KS9 {3, 4, 5}
41 -  KS10 {3, 4, 5}
42 -  KS11 {3, 4, 5}
43 -  KS12 {3, 4, 5}
44 -  KS13 {2, 3, 4, 5}
45 -  TT1 {2, 3, 4, 5}
46 -  TT2 {2, 3, 4, 5}
47 -  TT3 {2, 3, 4, 5}
48 -  TT4 {3, 4, 5}
49 -  GS1 {3, 4, 5}
50 -  GS2 {2, 3, 4, 5}
51 -  GS2.1 {2, 3, 4, 5}
52 -  GS4 {2, 3, 4, 5}
53 -  HH1 {2, 3, 4, 5}
54 -  HH2 {3, 4, 5}
55 -  HH3 {3, 4, 5}
56 -  HH4 {3, 4, 5}
57 -  HH5 {3, 4, 5}

Lọc dữ liệu nghiên cứu:
+ Môi trường (đang công tác hoặc đã công tác)
    Một trong các môi trường sau:
        1.1.	Công ty sản xuất Tôn
        1.2.	Công ty dịch vụ kiểm toán/ kế toán/ tư vấn (Có thực hiện dịch vụ kiểm toán/ kế toán/ tư vấn công ty sản xuất Tôn)
        1.3.	Trường đại học/ học viện đào tạo khối ngành kinh tế
+ Kinh nghiệm (đang công tác hoặc đã công tác)
    Đáp ứng đồng thời các điều kiện kinh nghiệm sau:
        2.	Ít nhất đã hoặc đang làm/ giảng dạy một trong các lĩnh vực về: kế toán, tài chính, kiểm toán, kiểm soát nội bộ, bán hàng, sản xuất, nhân sự, tổng hợp, quản lý
        3.	Ít nhất 1 năm kinh nghiệm trong lĩnh vực thuộc mục (2) và trong môi trường thuộc mục (1)
        4.	Chức danh công việc từ nhân viên trở lên

2.2a Linh_vuc_hoat_dong Column

Chỉ chấp nhận công ty sản xuất, công ty dịch vụ kiểm toán/ kế toán/ tư vấn và các trường đại học/ học viện đào tạo khối ngành kinh tế
    + San xuat
    + Giao duc

In [40]:
print(set(df['Linh_vuc_hoat_dong']))

{'Gia cong', 'Giao duc', 'San xuat', 'Thuong mai'}

In [41]:
## Thống kê số lượng các phần tử có trong cột

count = df['Linh_vuc_hoat_dong'].value_counts()
print(count)

San xuat      82
Thuong mai     5
Giao duc       2
Gia cong       2
Name: Linh_vuc_hoat_dong, dtype: int64

In [42]:
## Xóa các dòng có 'Gia cong', 'Thuong mai'

df = df[df['Linh_vuc_hoat_dong'] != 'Gia cong']
df = df[df['Linh_vuc_hoat_dong'] != 'Thuong mai']
df

,Ho_va_ten,So_dien_thoai_hoac_email,Gioi_tinh,Do_tuoi,Tham_nien_cong_tac,Noi_lam_viec,Nganh,Chuc_vu,Bo_phan,Loai_hinh_doanh_nghiep,...,TT4,GS1,GS2,GS2.1,GS4,HH1,HH2,HH3,HH4,HH5
0,Kieu Anh,ngothikieuanh281002@gmail.com,Nu,Duoi 30,Tu 1 den duoi 3 nam,Tap doan Hoa Sen,Ton thep,Nhan vien,Ke toan,Cong ty co phan,...,5,5,4,3,3,5,5,5,4,3
1,Dang Bao Ngan,708631096,Nu,Duoi 30,Tu 3 den duoi 5 nam,Thep Nam Kim,Ton thep,Nhan vien,Tai chinh,Cong ty co phan,...,3,5,4,4,3,5,4,4,5,5
2,Tran Cao Nam Anh,trancaonamanh93@gmail.com,Nu,Duoi 30,Tu 3 den duoi 5 nam,Tap doan Hoa Sen,Ton thep,Nhan vien,Ke toan,Cong ty co phan,...,4,4,4,5,5,2,5,3,4,3
3,Nguyen Cong Hung,981163301,Nam,Tu 30 den 39,Tu 5 den duoi 10 nam,Tap doan Hoa Sen,Ton thep,Giam doc/ Pho giam doc,Mua hang,Cong ty co phan,...,5,5,5,5,4,4,3,5,5,4
4,Ho Dieu,325791256,Nu,Duoi 30,Tu 1 den duoi 3 nam,Ton Dong A,Ton thep,Nhan vien,Ke toan,Cong ty co phan,...,3,4,4,3,4,2,3,5,4,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,Pham Van Dinh,NaN,Nam,Duoi 30,Tu 1 den duoi 3 nam,Thep Nam Kim,Ton thep,Nhan vien,Ke toan,Cong ty co phan,...,5,5,5,5,5,5,4,5,4,4
87,Tran Van Bao,923713103,Nam,Duoi 30,Tu 3 den duoi 5 nam,Tap doan Hoa Sen,Ton thep,To truong/ To pho,Ban hang,Cong ty co phan,...,3,5,3,5,3,4,4,5,3,4
88,Nguyen Van An,389286105,Nam,Duoi 30,Tu 3 den duoi 5 nam,Tap doan Hoa Sen,Ton thep,Nhan vien,Ke toan,Cong ty co phan,...,3,3,5,4,4,3,5,5,4,5
89,Ho Van Hong Hanh,366736024,Nu,Duoi 30,Tu 3 den duoi 5 nam,Tap doan Hoa Phat,Ton thep,Nhan vien,Ban hang,Cong ty co phan,...,5,4,4,5,3,5,5,4,3,5
90,Nguyen Van Thi,976894036,Nam,Duoi 30,Tu 3 den duoi 5 nam,Tap doan Hoa Sen,Ton thep,Nhan vien,Ky thuat,Cong ty co phan,...,5,4,4,5,3,5,4,5,4,4

In [43]:
## Check đã drop được các phần tử không phải là 'Gia cong', 'Thuong mai' trong cột Linh_vuc_hoat_dong hay chưa

count = df['Linh_vuc_hoat_dong'].value_counts()
print(count)

San xuat    82
Giao duc     2
Name: Linh_vuc_hoat_dong, dtype: int64

2.2b Tham_nien_cong_tac column

Dữ liệu có thâm niên công tác dưới 1 năm sẽ bị loại bỏ

In [44]:
print(set(df['Tham_nien_cong_tac']))

{'Tu 10 nam tro len', 'Tu 1 den duoi 3 nam', 'Tu 3 den duoi 5 nam', 'Tu 5 den duoi 10 nam'}

In [45]:
## Thống kê số lượng các phần tử có trong cột

count = df['Tham_nien_cong_tac'].value_counts()
print(count)

Tu 3 den duoi 5 nam     36
Tu 1 den duoi 3 nam     32
Tu 5 den duoi 10 nam     9
Tu 10 nam tro len        7
Name: Tham_nien_cong_tac, dtype: int64

--> Ta thấy không có thâm niên công tác dưới 1 năm

==> DỮ LIỆU ĐÃ SẠCH VÀ CÓ THỂ TIẾP TỤC SỬ DỤNG CHO PHÂN TÍCH TIẾP THEO

TASK 3: PHÂN TÍCH DỮ LIỆU


Theo kết quả nghiên cứu định tính, ta có mô hình hồi quy đa biến sau:
    HH = β0 + β1 x MT + β2 x RR + β3 x KS + β4 x TT + β5 x GS + e

Trong đó:
    HH	: Tính hữu hiệu (biến phụ thuộc)
    MT	: Môi trường kiểm soát (biến độc lập)
    RR	: Đánh giá rủi ro (biến độc lập)
    KS	: Hoạt động kiểm soát (biến độc lập)
    TT	: Hệ thống thông tin và truyền thông (biến độc lập)
    GS	: Hoạt động giám sát (biến độc lập)
    β0	: Hằng số
    β1, β2, β3, β4, β5	: Hệ số các biến độc lập (hệ số hồi quy)
    e	: Phần dư

In [46]:
## 3.1 Thống kê mô tả các biến

df.describe()

,MT1,MT2,MT3,MT4,MT5,MT6,MT7,MT8,MT9,MT10,...,TT4,GS1,GS2,GS2.1,GS4,HH1,HH2,HH3,HH4,HH5
count,84.000000,84.000000,84.000000,84.000000,84.000000,84.000000,84.000000,84.000000,84.000000,84.000000,...,84.000000,84.000000,84.000000,84.000000,84.000000,84.000000,84.000000,84.000000,84.000000,84.000000
mean,3.845238,3.773810,3.785714,3.857143,3.678571,4.273810,3.857143,4.119048,4.107143,4.142857,...,4.095238,4.095238,4.059524,4.119048,3.690476,4.107143,4.047619,4.000000,4.023810,4.178571
std,0.950511,0.961314,0.892694,0.808730,0.823754,0.811828,0.958700,0.812623,0.836197,0.823493,...,0.886567,0.844815,0.855192,0.910511,0.904822,0.931612,0.876806,0.864285,0.821051,0.866522
min,2.000000,1.000000,2.000000,2.000000,2.000000,3.000000,2.000000,3.000000,3.000000,3.000000,...,3.000000,3.000000,2.000000,2.000000,2.000000,2.000000,3.000000,3.000000,3.000000,3.000000
25%,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,3.000000,3.000000,3.000000,3.000000,...,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,3.000000,3.000000,3.000000,3.000000
50%,4.000000,4.000000,4.000000,4.000000,3.500000,4.500000,4.000000,4.000000,4.000000,4.000000,...,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000
75%,5.000000,5.000000,4.000000,4.000000,4.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,4.000000,5.000000,5.000000,5.000000,5.000000,5.000000
max,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

# 3.2 Kiểm định độ tin cậy bằng hệ số Cronbach’s Alpha

Kiểm định độ tin cậy bằng hệ số Cronbach’s Alpha là phép kiểm định mức độ tương quan chặt chẽ giữa các biến quan sát với nhau trong cùng một nhân tố, nghĩa là, Cronbach’s Alpha cho biết các biến quan sát của một nhân tố, biến nào đóng góp vào việc đo lường khái niệm nhân tố, biến nào không.

Điều kiện để xét hệ số Cronbach's Alpha phù hợp là:
    + Theo Nguyễn Đình Thọ (2013) có chỉ ra một số điều kiện lý thuyết:
        - Hệ số Cronbach’s Alpha chỉ đo lường độ tin cậy của thang đo (từ 3 biến quan sát trở lên), không tính được độ tin cậy cho từng biến quan sát;
        - Hệ số Cronbach’s Alpha có giá trị biến thiên trong đoạn từ 0 đến 1. Về lý thuyết, hệ số này càng cao thì thang đo có độ tin cậy càng cao. Tuy nhiên nếu hệ số quá lớn ≥ 0,95 có khả năng có nhiều biến trong thang đo bị trùng lắp.
    + Theo Nunnally (1978), hệ số Cronbach’s Alpha > 0,6 thì thang đo lường đủ điều kiện.

=> Nghĩa là Cronbach’s Alpha cần > 0,6 và < 0,95 thì đạt độ tin cậy.

In [55]:
##Drop các dữ liệu không phải dạng số để tính Cronbach's Alpha

data = df.drop(columns=['Ho_va_ten', 'So_dien_thoai_hoac_email', 'Gioi_tinh', 'Do_tuoi', 'Tham_nien_cong_tac', 'Noi_lam_viec', 'Nganh', 'Chuc_vu', 'Bo_phan', 'Loai_hinh_doanh_nghiep', 'Linh_vuc_hoat_dong', 'Quy_mo'])
data

,MT1,MT2,MT3,MT4,MT5,MT6,MT7,MT8,MT9,MT10,...,TT4,GS1,GS2,GS2.1,GS4,HH1,HH2,HH3,HH4,HH5
0,5,5,5,3,3,3,3,5,3,4,...,5,5,4,3,3,5,5,5,4,3
1,4,5,4,4,4,5,4,5,4,3,...,3,5,4,4,3,5,4,4,5,5
2,5,5,4,4,5,5,4,5,5,5,...,4,4,4,5,5,2,5,3,4,3
3,4,4,4,5,5,4,4,4,5,4,...,5,5,5,5,4,4,3,5,5,4
4,5,5,2,4,3,4,3,4,3,4,...,3,4,4,3,4,2,3,5,4,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,3,3,4,5,5,5,5,5,5,5,...,5,5,5,5,5,5,4,5,4,4
87,4,4,4,5,3,3,5,4,4,3,...,3,5,3,5,3,4,4,5,3,4
88,3,3,4,3,3,5,3,3,4,5,...,3,3,5,4,4,3,5,5,4,5
89,4,4,2,3,4,4,3,3,3,5,...,5,4,4,5,3,5,5,4,3,5
90,5,5,4,5,5,4,5,5,3,3,...,5,4,4,5,3,5,4,5,4,4

In [62]:
data.columns[1]

'MT2'

In [58]:
##Tính Cronbach Alpha
pg.cronbach_alpha(data)

(0.9162703534213439, array([0.889, 0.94 ]))

==> Cronbach's Alpha = 0.916 > 0.65 và < 0.95 cho nên dữ liệu đạt độ tin cậy và có thể sử dụng cho phân tích tiếp theo.

TASK 4: VẼ BIỂU ĐỒ